# Generated by Django 5.2.6 on 2025-09-29 15:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuniorTestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسجيل')),
                ('has_taken_test', models.BooleanField(default=False, verbose_name='أخذ الاختبار')),
            ],
            options={
                'verbose_name': 'تسجيل اختبار الناشئين',
                'verbose_name_plural': 'تسجيلات اختبار الناشئين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuniorTrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السمة')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Trait Name (English)')),
                ('weight', models.IntegerField(help_text='القيمة النسبية لهذه السمة (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='الوزن النسبي')),
                ('description', models.TextField(blank=True, verbose_name='وصف السمة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سمة ريادية للناشئين',
                'verbose_name_plural': 'السمات الريادية للناشئين',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JuniorTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بدأ في')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='انتهى في')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('answers_json', models.TextField(blank=True, verbose_name='الإجابات (JSON)')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_session', to='main.juniortestregistration', verbose_name='التسجيل')),
            ],
            options={
                'verbose_name': 'جلسة اختبار الناشئين',
                'verbose_name_plural': 'جلسات اختبار الناشئين',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JuniorTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='الدرجة الكلية (%)')),
                ('trait_scores_json', models.TextField(verbose_name='درجات السمات (JSON)')),
                ('certificate_path', models.CharField(blank=True, max_length=500, verbose_name='مسار الشهادة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('time_taken_minutes', models.IntegerField(default=0, verbose_name='الوقت المستغرق (دقائق)')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main.juniortestsession', verbose_name='الجلسة')),
            ],
            options={
                'verbose_name': 'نتيجة اختبار الناشئين',
                'verbose_name_plural': 'نتائج اختبارات الناشئين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JuniorQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.juniortrait', verbose_name='السمة المرتبطة')),
            ],
            options={
                'verbose_name': 'سؤال الناشئين',
                'verbose_name_plural': 'أسئلة الناشئين',
                'ordering': ['order'],
            },
        ),
    ]
