# Generated by Django 5.2.6 on 2025-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_trait_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniorquestion',
            name='is_reverse_scored',
            field=models.BooleanField(default=False, help_text='إذا كانت الإجابة الإيجابية تعني درجة منخفضة', verbose_name='عكس التقييم'),
        ),
    ]
