# Generated by Django 5.2.6 on 2025-10-02 19:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_juniorquestion_is_reverse_scored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juniortrait',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='القيمة النسبية لهذه السمة (0.01-100.00)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='الوزن النسبي'),
        ),
    ]
